title: Yai
title_separator: "|"
email: noknok@gmail.com
repository: "mounta11n/yai"
description: >-
  Yai ("Your AI") ist ein Terminal-Assistent mit k端nstlicher Intelligenz.
 Mit ihm kannst du beliebige Befehlszeilen aus Anfragen vorbereiten und ausf端hren, die du in deiner nat端rlichen Sprache formulierst.
 Du kannst dich auch mit ihm 端ber alle Themen unterhalten, die dir in den Sinn kommen.
 Entfessle die Macht der KI mit dem Komfort, zu Hause zu bleiben!
twitter_username: noxekki
github_username: mounta11n
minimal_mistakes_skin: dark
search: false
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Jonathan Vuillemin"
  avatar : "https://avatars.githubusercontent.com/u/6922385?s=400&u=87b8f6b9674c3667b1a75e294387c7af3e335b69&v=4"
  bio    : "Backend and other things."
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/noxekki"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mounta11n"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/noxekki"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mounta11n"

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: splash
      author_profile: false
